spring.application.name=deliverymen

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=urbanfood_user
spring.datasource.password=urban123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.profiles.active=dev
server.port=8081

# Mongodb config
spring.data.mongodb.uri=mongodb://localhost:27017/urbanfood


# Hibernate Configuration
# Use 'create' for initial setup, 'update' for ongoing updates
spring.jpa.hibernate.ddl-auto=update

# Display SQL queries in logs for debugging
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true
# Define the location of static resources
spring.resources.static-locations=file:///C:\Users\suham\Downloads\ProjectPictures/

# Define the URL pattern to access these resources
spring.web.resources.static-path-pattern=/images/**
